---
# Travis builds are run in Arch Linux docker containers so we have access to
# gcc8: https://github.com/mikkeloscar/arch-travis
sudo: required

services:
    - docker

archlinux:
    packages:
        - avr-binutils
        - avr-gcc
        - avr-libc
        - make
        - stack
    script:
        - make all
        - cd ui; stack build -j2

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
