name:                color-test
version:             0.1.0.0
github:              "Rave-Saber/AVR-APA102-Color-Tester"
license:             GPL-3.0
author:              "Pavan Rikhi"
maintainer:          "pavan.rikhi@gmail.com"
copyright:           "GPL-3.0"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Rave-Saber/AVR-APA102-Color-Tester#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executable:
  main:                Main.hs
  source-dirs:         app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  dependencies:
  - color-test
  - brick
  - bytestring
  - serialport
  - vector
  - vty
  - lens
